# Use root/example as user/password credentials
version: '3.4'

services:

  db:
    image: mysql:5.7
    container_name: cn-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my-network
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network

networks:
  my-network: